#include "undef_side_gear.hpp"  
#define SIDE_KEY "ACE_key_civ"
#define SIDE_CHEM_LIGHT "Chemlight_yellow:2"
#define SIDE_UAV_BACKPACK "C_IDAP_UAV_01_backpack_F" 
#define SIDE_UAV_TERMINAL "C_uavterminal" 
